# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hoang
tagline:          'Personal blog of a nerd at heart'
description:      'Personal blog of a nerd at heart. <a href="https://twitter.com/anhiliate" target="_blank">@anhiliate</a>'
url:              https://anhiliate.github.io
baseurl:          /

author:
  name:           'Anh Hoang'
  url:            https://twitter.com/anhiliate

paginate:         5

# Custom vars
version:          2.1.0
gems: 
  - jekyll-paginate
  - jemoji
port: 4001

github:
  repo:           https://github.com/anhiliate
